Parameters:
  AcmCertificateArn:
    Type: String
  Aliases:
    Type: String
  APIDomainName: 
    Type: String
  APILoggingBucket:
    Type: String

Resources:
  GenoVicCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref Aliases
        Origins:
        - DomainName: !Ref APIDomainName
          Id: testapigwy
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
            - POST
            - OPTIONS
            - PATCH
            - DELETE 
            - PUT
          CachedMethods: 
            - GET
            - HEAD
          MinTTL: 100
          DefaultTTL: 100
          MaxTTL: 300
          ForwardedValues:
             QueryString: false
             Cookies:
               Forward: all 
          TargetOriginId: testapigwy
          ViewerProtocolPolicy: allow-all
        Logging:
          Bucket: !Ref APILoggingBucket
          IncludeCookies: false
          Prefix: Cloudfront-APIGWY/
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Restrictions:
          GeoRestriction:
            Locations:
              - "AU"
            RestrictionType: whitelist 