Parameters:
  ALB1domainName:
    Type: String 

  ALB2domainName:
    Type: String


  AcmCertificateArn:
    Type: String


Resources:
  MyCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
        - DomainName: !ImportValue genovic-gos-devdaniel-ApiGatewayDnsName
          Id: testapigwy
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        - DomainName: !Ref ALB1domainName
          Id: testalb1
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        - DomainName: !Ref ALB2domainName
          Id: testalb2
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
          OriginShield:
            Enabled: True 
            OriginShieldRegion: ap-southeast-2
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          MinTTL: 100
          DefaultTTL: 100
          MaxTTL: 300
          ForwardedValues:
             QueryString: true
          TargetOriginId: testapigwy
          ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Restrictions:
          GeoRestriction:
            Locations:
              - "AU"
            RestrictionType: whitelist
        
        
  