Parameters:
  ALB1domainName:
    Type: String 
  ALB2domainName:
    Type: String
  AcmCertificateArn:
    Type: String

Resources:
  MyCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: 
          - deloitte.labtec.genovic.org.au
          - gosdaniel.sandbox-external.genovic.org.au
        Origins:
        - DomainName: !ImportValue genovic-gos-devdaniel-ApiGatewayDnsName
          Id: testapigwy
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        - DomainName: !Ref ALB1domainName
          Id: testalb1
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        - DomainName: !Ref ALB2domainName
          Id: testalb2
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
          OriginShield:
            Enabled: True 
            OriginShieldRegion: ap-southeast-2
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          MinTTL: 100
          DefaultTTL: 100
          MaxTTL: 300
          TargetOriginId: testapigwy
          ViewerProtocolPolicy: allow-all
          CachePolicyId: !Ref GenoVicCFCacheConfig1
        CacheBehaviors:
          - Compress: false
            DefaultTTL: 100
            MaxTTL: 300
            MinTTL: 100
            PathPattern: /deloitte.labtec.genovic.org.au/*
            SmoothStreaming: false
            TargetOriginId: testalb1
            ViewerProtocolPolicy: allow-all
            CachePolicyId: !Ref GenoVicCFCacheConfig1
          - Compress: false
            DefaultTTL: 100
            MaxTTL: 300
            MinTTL: 100
            PathPattern: /cslb
            SmoothStreaming: false
            TargetOriginId: testalb2
            ViewerProtocolPolicy: allow-all
            CachePolicyId: !Ref GenoVicCFCacheConfig1
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Restrictions:
          GeoRestriction:
            Locations:
              - "AU"
            RestrictionType: whitelist
  GenoVicCFCacheConfig1:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 100
        MaxTTL: 300
        MinTTL: 100
        Name: GenoVicCFCache
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Origin
          QueryStringsConfig:
            QueryStringBehavior: none
        
        
  