Resources:
  GenoVicCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
        - DomainName: !ImportValue genovic-gos-devdaniel-ApiGatewayDnsName
          Id: testalb
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          MinTTL: 100
          DefaultTTL: 100
          MaxTTL: 300
          ForwardedValues:
             QueryString: true
          TargetOriginId: testalb
          ViewerProtocolPolicy: allow-all
          CachePolicyId: !Ref GenoVicCFCacheConfig
  
  GenoVicCFCacheConfig:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 100
        MaxTTL: 300
        MinTTL: 100
        Name: GenoVicCFCache
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: false
          EnableAcceptEncodingGzip: false
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Origin
          QueryStringsConfig:
            QueryStringBehavior: none