Parameters:
  S3URI:
    Type: String 

Resources:
    CloudFormationCanaryPack:
        Type: AWS::Config::ConformancePack
        Properties:
          ConformancePackName: TRY1PACK
          TemplateS3Uri: !Ref S3URI
            

    