Parameters:
  AggRegion:
    Description: AWS Region for Aggregator
    Type: String

  AggAccount:
    Description: AWS Account ID of Aggregator
    Type: String


AggregationAuthorization: 
  Type: "AWS::Config::AggregationAuthorization"
  Properties: 
    AuthorizedAccountId: !Ref AggAccount
    AuthorizedAwsRegion: !Ref AggRegion