Parameters:
  AggRegion:
    Description: AWS Region for Aggregator
    Type: String

  AggAccount:
    Description: AWS Account ID of Aggregator
    Type: String

Resources:
    MyAggregationAuthorization: 
      Type: "AWS::Config::AggregationAuthorization"
      Properties: 
        AuthorizedAccountId: !Ref AggAccount
        AuthorizedAwsRegion: !Ref AggRegion