Resources:
  TestEventBus:
    Type: AWS::Events::EventBus
    Properties: 
      Name: TestEventBus

Outputs:     
  EventBusName:
    Description: Name of Event Bus
    Value: !Ref TestEventBus
    Export:
      Name: TestEventBusName
  EventBusARN:
    Description: Arn of Event Bus
    Value: !GetAtt TestEventBus.Arn
  
    
