Resources:
  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.securityhub
        detail-type:
          - Security Hub Findings - Imported
        detail:
          findings:
            ProductArn:
              - arn:aws:securityhub:ap-southeast-1::product/aws/guardduty
            Severity:
              Label:
                - HIGH
                - CRITICAL
      Name: CFTestRule
      State: ENABLED
      Targets:
        - Id: DeloitteEmailSNSTopic
          Arn: !ImportValue SNStopicArn