AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DetectId:
    Type: String 
  MembrID1:
    Type: String
  emailID:
    Type: String
  MembrID2:
    Type: String

Resources:
  GuardDutyMember1:
    Type: AWS::GuardDuty::Member
    Properties: 
      DetectorId: !Ref DetectId
      MemberId: !Ref MembrID1
      Email: !Ref emailID
      Message: "Invitation to join GuardDuty"
      Status: "Invited"
  GuardDutyMember2:
    Type: AWS::GuardDuty::Member
    Properties: 
      DetectorId: !Ref DetectId
      MemberId: !Ref MembrID2
      Email: !Ref emailID
      Message: "Invitation to join GuardDuty"
      Status: "Invited"
