Resources:
  TestSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: TestSNSTopic1
      SignatureVersion: 2

Outputs:
  TestSNSoutput: 
    Value: !Ref TestSNSTopic
    Export:
      Name: SNStopicArn
