Parameters:
  destinationS3Arn:
    Type: String
  sources3Arn: 
    Type: String

Resources: 
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: 
            Service: 
             - s3.amazonaws.com
          Action: 
            - sts:AssumeRole
      Description: Role for cross account access
      Path: /
      Policies: 
        - PolicyName: S3CrossAccountReplicationPolicyv2
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
            - Effect: Allow 
              Action: 
                -  s3:*
              Resource: 
                - !Ref sources3Arn
            - Effect: Allow 
              Action: 
                - s3:*
              Resource: 
                - !Ref destinationS3Arn 
      RoleName: S3CrossAccountReplicationRoleV2


Outputs:
     IAMroleArnOutput: 
      Description: Arn of the IAM role 
      Value: !GetAtt CrossAccountRole.Arn 
      Export: 
          Name: ExportofCrossAccountRoleArnv2